queue_rules:
  - name: default
    merge_conditions:
      - check-success=self-test (macos-latest)
      - check-success=self-test (macos-latest, --no-nom)
      - check-success=self-test (ubuntu-latest)
      - check-success=self-test (ubuntu-latest, --no-nom)
      - check-success=tests (macos-latest)
      - check-success=tests (ubuntu-latest)
defaults:
  actions:
    queue:
      merge_method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label~=merge-queue|dependencies
    actions:
      queue: {}
