queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - label~=merge-queue|dependencies
    merge_conditions:
      - check-success=self-test (macos-latest)
      - check-success=self-test (macos-latest, --no-nom)
      - check-success=self-test (ubuntu-latest)
      - check-success=self-test (ubuntu-latest, --no-nom)
      - check-success=tests (macos-latest)
      - check-success=tests (ubuntu-latest)
      - check-success=buildbot/nix-build
    merge_method: rebase

pull_request_rules:
  - name: merge using the merge queue
    conditions: []
    actions:
      queue:
